### ISSUE TITLE
Breaks OpenVR/OVR in standalone windows build

### ISSUE THREAD

**Issue by jletellier** [googleprivate/resonance-audio-unity-sdk#33]
The plugin works perfectly in the Unity editor with or without OpenVR. However, as soon as I build a Windows x86/x64 version it prevents the HTC Vive/Oculus Rift from launching. The application will not even attempt to connect to a VR device, however the applications itself and the spatializer/ambisonics work as expected. The error logs do not show anything related to VR. 

I tested the following versions:
- Resonance Audio SDK for Unity v1.2.1 (with Unity 2018.1.0)
- Resonance Audio SDK for Unity v1.2.0 (with Unity 2018.1.0 and Unity 2017.4.2)

As soon as I disable the spatializer in Unity's audio settings, the application works with all VR devices.

Am I missing something obvious here?

**Comment by GaelFG** [comment]
I have the exact same issue on unity 2018.1.0f2.

To reproduce :  
- Create a new empty project in unity 2018.1.0f2.

- Go on Edit, Project Settings, Player
- On XR Setting check Virtual Reality Supported
- (maybe optionnal) Suppress Oculus from the Virtual Reality SDK so that OpenVR is alone
- Click on File -> Build & Run
- Game should launch without issue on your VR HDM
- Go on Edit, Project Settings, Audio
- Choose Resonance Audio as Spatializer Plugin
- Click on File -> Build & Run
- Game should launch on fallback standard mode and show an error about a  missing openvr dll

**Comment by GaelFG** [comment]
Unity QA responded to the issue on unity : 

I've taken a look at the mentioned plugin and the problem seems to lie that the editor includes an additional dll for the plugin as of 2018.1. A workaround for now would be to go to the build's plugin folder and delete the x86_64 folder, but I will forward this to the developers for further resolution.

The work around worked for me.

**Comment by jletellier** [comment]
That did the trick for me. Thank you very much!
